# Generated by Django 3.0.8 on 2020-07-10 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200709_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['-value']},
        ),
        migrations.RemoveField(
            model_name='listing',
            name='current_bid',
        ),
    ]
