# Generated by Django 3.0.8 on 2020-07-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_watch'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('TR', 'Travel'), ('FD', 'Food'), ('CL', 'Clothing'), ('AV', 'Adventure'), ('OT', 'Other')], default='TR', max_length=2, null=True),
        ),
    ]
