# Generated by Django 3.0.8 on 2020-07-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200711_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('TR', 'Travel'), ('FD', 'Food'), ('CL', 'Clothing'), ('AV', 'Adventure'), ('OT', 'Other')], max_length=2),
        ),
    ]
